### ISSUE TITLE
Why is FetchError is not using the Response object?

### ISSUE THREAD

**Issue by thewizarodofoz** [Soluto/tweek-clients#156]
The js client [throws](https://github.com/Soluto/tweek-clients/blob/master/js/tweek-client/src/TweekClient/TweekClient.ts#L98) a [`FetchError`](https://github.com/Soluto/tweek-clients/blob/master/js/tweek-client/src/FetchError.ts) with the `Response` object but it does not use it in the error object. I believe it is obscuring the real reason for the error.

**Comment by Yshayy** [comment]
I think the error object would have a response property
