### ISSUE TITLE
Preparing scan path doesn't work

### ISSUE THREAD

**Issue by ZahiC** [Soluto/tweek-clients#37]
Seems like the scan path is fetched from tweek, but then, when a specific key is requested, it is reported as missing.

tweekRepository.prepare('some_category/_')
tweekRepository.refresh()
tweekRepository.get('some_category/some_key')

Getting error: 'key some_category not managed, use prepare to add it to cache'

**Comment by nataly87s** [comment]
@ZahiC I think this issue still relevant?

**Comment by ZahiC** [comment]
If I recall, @Yshayy may added a fix. But I'm not sure. @Yshayy?

**Comment by Yshayy** [comment]
It looks like it covered:
https://github.com/Soluto/tweek-clients/blob/master/js/tweek-local-cache/spec/unit/tweek-repository.spec.ts#L161
