### ISSUE TITLE
tweek-local-cache: add the ability to set a list of paths that will not be refreshed

### ISSUE THREAD

**Issue by guysegal** [Soluto/tweek-clients#46]
While developing you want to get the refreshed keys from Tweek server, however sometimes you need to change values of a key locally to test or try something. tweek-local-cache will refresh your keys once you'll call `refresh` method.

Maybe adding a black list for keys that you don't want to be refreshed will be useful. I can't think of a production scenario for it, but as mentioned it can be useful for development.

What do you think?

**Comment by nataly87s** [comment]
We added an option to refresh a list of keys, is it good enough?
