### ISSUE TITLE
Add multiple keys support to withTweekKeys

### ISSUE THREAD

**Issue by AvivRubys** [Soluto/tweek-clients#49]
We've run into some issues where our components begin to look like this:
```
const MyComponent = compose(
    withTweekKeys('some/tweek/key/1'),
    withTweekKeys('another/tweek/key/1'),
    withTweekKeys('some/other/key'),
)(SomeComponent);
```

Perhaps withTweekKeys could handle more than one key? This would also make it more efficient as there would be less components in the tree when using more than one key.

**Comment by nataly87s** [comment]
What do you think about this api:

```withTweekKeys ([keyPath], [mapValueToProps], [options])```

and the `options` argument should have these props:
- `include` - just like tweek-api's include - for more than one key
-  `getPolicy` - tweek-local-cache getPolicy
- `onError` - handle errors

**Comment by Yshayy** [comment]
What about passing object:
{
myProp:"keypath1"
...
} As the first argument (it can also accept strings for simple cases and backward compatibility), the second arg can be the options.

**Comment by nataly87s** [comment]
I have 2 reasons for what i suggested:
1. to stay compatible with the rest of tweeks' clients
2. it's more similar to [react-redux connect](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options)

**Comment by Yshayy** [comment]
I think redux connect API is too verbose for our cases, how it affects compatibility?

**Comment by nataly87s** [comment]
In the .Net client and in the js client when you want multiple keys you use `include`, I think it should stay the same here so you know exactly what you expect the result to be

**Comment by AvivRubys** [comment]
I think adding a `mapValueToProps` function is probably too much - 99% of the time you'd just map the values to an object.
@Yshayy 's solution is not as compatible to the other tweek APIs as it could be, but on the other hand it is simple and has an obvious meaning to people who aren't familiar with `include`. (Also its almost identical to the withConfigs HOC inside Home)
It's worth mentioning that neither of these options have support for defaults. Are we just assuming the components would use something like `defaultProps`?

**Comment by nataly87s** [comment]
I guess @Yshayy 's solution is more simple, but if we start adding backwards compatibility to it - it actually makes it more complicated imho.
We can loose the `mapValueToProps` and keep the behavior we have now with the `propName` and `mergeProps` options we currently have, but add the `include` option for multiple keys

**Comment by nataly87s** [comment]
and about the `defaultProps`, if we add support for defaults, I think it should be at the tweek-local-cache level, so that the defaults are the same for all the consumers

**Comment by Yshayy** [comment]
I think it's ok if React Tweek api will be different then the other, since it's more data-binding like api. (it designed for UI).
As for defaults, it can be solved by applying default at prop level, for example:
```
withTweekValue({someProp:"path_to_key"})(({someProp="defaultValue"})=> <div>{someProp}</div>
```

**Comment by Yshayy** [comment]
It's also possible to allow more complex definition for each pair:
withTweekValue({someProp: {key:"path_to_key", defaultValue:"bla"})(({someProp})=> <div>{someProp}</div>

**Comment by nataly87s** [comment]
@Yshayy did we decide anything? I might have some time to work on this

**Comment by orenklein** [comment]
@nataly87s @Yshayy Anything new?

**Comment by nataly87s** [comment]
@orenklein we're not working on this, you can add this feature if you want

**Comment by nataly87s** [comment]
done in #116
