### ISSUE TITLE
Failed reading suubtree of configuration keys in iOS

### ISSUE THREAD

**Issue by AharonDror** [Soluto/tweek-clients#59]
I'm using @npmsoluto/react-tweek, version 0.3.11
In my react-native app, as a high-order component, I'm using withTweekKeys with a tree subset (i.e. `path/to/subset/_`).
On Android everything works as planned, on iOS I get a failure in initialization with the message:
"value not available yet for key: path/to/subset/_"

**Comment by nataly87s** [comment]
In the current version of `tweek-local-cache` (`0.2.1`) you can add a policy for what to do if the value is not available yet.
